import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from './components/theme-provider'
import { Providers } from './modules/provider'
import ProviderWrapper from './modules/ProviderWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Multistreams',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ptbr">
      <body className={inter.className}>
        <ProviderWrapper>
          <ThemeProvider attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange>
            <Providers>
              {children}
            </Providers>
          </ThemeProvider>
        </ProviderWrapper>
      </body>
    </html>
  )
}
